# Generated by Django 4.0.4 on 2022-06-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='apellido',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='correo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='nombre',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
