# Generated by Django 4.0.4 on 2022-06-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_apellido_user_profile_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='profile_image',
            field=models.ImageField(default='', upload_to='profile_image'),
        ),
    ]
