# Generated by Django 4.0.4 on 2022-07-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='correo',
            field=models.CharField(default='', max_length=25),
        ),
    ]
