# Generated by Django 4.0.4 on 2022-06-04 09:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen', models.IntegerField(blank=True, null=True)),
                ('medida', models.CharField(blank=True, choices=[('lts', 'lts'), ('ml', 'ml')], max_length=3, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Capacidades',
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(blank=True, null=True)),
                ('fecha_alta', models.DateField(blank=True, default=datetime.datetime(2022, 6, 4, 9, 20, 25, 977737, tzinfo=utc), null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Envase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('Botella', 'Botella'), ('Lata', 'Lata')], max_length=7, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('capacidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage_product.capacidad')),
            ],
        ),
        migrations.CreateModel(
            name='Cerveza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('abv', models.IntegerField(blank=True, null=True)),
                ('ibu', models.FloatField(blank=True, null=True)),
                ('brew', models.CharField(blank=True, choices=[('Ale', 'Ale'), ('Lager', 'Lager')], max_length=5, null=True)),
                ('color', models.CharField(blank=True, choices=[('Golden', 'Golden'), ('Red', 'Red'), ('Black', 'Black')], max_length=6, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('envase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_product.envase')),
                ('precio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_product.precio')),
            ],
        ),
    ]
