# Generated by Django 4.0.4 on 2022-07-03 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elaborador', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Envase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('Botella', 'Botella'), ('Lata', 'Lata')], max_length=7, null=True)),
                ('volumen', models.IntegerField(blank=True, null=True)),
                ('medida', models.CharField(blank=True, choices=[('lts', 'lts'), ('ml', 'ml')], max_length=3, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cerveza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('abv', models.IntegerField(blank=True, null=True)),
                ('ibu', models.FloatField(blank=True, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('Ale', 'Ale'), ('Lager', 'Lager')], max_length=5, null=True)),
                ('color', models.CharField(blank=True, choices=[('Golden', 'Golden'), ('Red', 'Red'), ('Black', 'Black')], max_length=6, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('brew', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brews', to='manage_product.brew')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='manage_product.categoria')),
                ('envase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envases', to='manage_product.envase')),
            ],
        ),
    ]
