# Generated by Django 4.0.4 on 2022-06-04 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0002_alter_precio_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='fecha_alta',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 4, 9, 23, 41, 598099, tzinfo=utc), null=True),
        ),
    ]
