# Generated by Django 4.0.4 on 2022-06-07 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0006_alter_precio_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='fecha_alta',
            field=models.DateField(blank=True, default=datetime.date(2022, 6, 7), null=True),
        ),
    ]
