# Generated by Django 4.0.4 on 2022-06-28 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0006_alter_precio_fecha_alta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elaborador', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='envase',
            name='capacidad',
        ),
        migrations.AddField(
            model_name='cerveza',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Ale', 'Ale'), ('Lager', 'Lager')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='envase',
            name='medida',
            field=models.CharField(blank=True, choices=[('lts', 'lts'), ('ml', 'ml')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='envase',
            name='volumen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cerveza',
            name='envase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envases', to='manage_product.envase'),
        ),
        migrations.AlterField(
            model_name='cerveza',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Capacidad',
        ),
        migrations.DeleteModel(
            name='Precio',
        ),
        migrations.AddField(
            model_name='cerveza',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='manage_product.categoria'),
        ),
        migrations.AlterField(
            model_name='cerveza',
            name='brew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brews', to='manage_product.brew'),
        ),
    ]
