# Generated by Django 4.0.4 on 2022-06-30 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0007_brew_categoria_remove_envase_capacidad_cerveza_tipo_and_more'),
        ('manage_product', '0009_alter_precio_fecha_alta'),
    ]

    operations = [
    ]
